### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by DZakh** [jderochervlk/netlify-functions#1]
I've noticed that you use my library `rescript-struct` and decided to take a look.

Here are some suggestions:

1. In [pattern matchings](https://github.com/jderochervlk/netlify-functions/blob/2875b736d52f1e03be0a8df51d0936d8c8896b10/src/netlify/functions/person.res#L18) you don't need to specify from which module `Ok` and `Error` comes. So you can change `Belt.Result.Ok`->`Ok` and `Belt.Result.Error`->`Error`, rescript compiler will figure out the rest.

2. Instead of `Belt` it's much better to use [`Core`](https://github.com/rescript-association/rescript-core)

3. The `rescript-struct`'s is an object with some data which is not in a very readable format (because of the way how variants compiled to Js). So [here](https://github.com/jderochervlk/netlify-functions/blob/2875b736d52f1e03be0a8df51d0936d8c8896b10/src/netlify/functions/person.res#L28) you can use [`err->S.Error.toString`](https://github.com/DZakh/rescript-struct#serrortostring) instead of `JSON.stringifyAny(err)`, to get a human-readable error message.

4. Hehe, a committed secret 😅 https://github.com/jderochervlk/netlify-functions/blob/2875b736d52f1e03be0a8df51d0936d8c8896b10/src/faunadb.res#L16

5. About accessing env variables like [here](https://github.com/jderochervlk/netlify-functions/blob/2875b736d52f1e03be0a8df51d0936d8c8896b10/src/faunadb.res#L1). I have a library [`rescript-envsafe`](https://github.com/DZakh/rescript-envsafe) to do it more reliably.

Besides this, I'm really happy to see new people in the ReScript community. Good luck!

**Comment by jderochervlk** [comment]
Thanks for the suggestions!

> Hehe, a committed secret 

You would think I would know better by now lol. I'll check out that library!

**Comment by jderochervlk** [comment]
I've gone ahead and made some changes based on your feedback. Thanks!
